server:
  port: 9001
spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/hat
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    dbcp2:
      default-schema: hat
app:
  jwt:
    secret-key: E5J5rFgqJ#3XFzadeth535t4efdbt67i86yrfv234
    expiration: 600000
