server:
  port: 9001
spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://192.168.133.6:5435/hat
    username: hatuser
    password: hatuser
    driver-class-name: org.postgresql.Driver
