name: Build & Measure code coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  publish-code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: liberica
      - name: Before Install
        run: |
          chmod +x gradlew
          chmod +x gradle/wrapper/gradle-wrapper.jar
      - name: Run Script
        run: |
          ./gradlew build -x detekt
      - name: Upload code coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
